### PR TITLE
Baseline chart

### PR DESCRIPTION
**Pull request by vgeorge**
Please refer to https://github.com/global-electrification-platform/explorer/issues/188.

This is being implemented in parallel with https://github.com/global-electrification-platform/data-service/pull/70, as baseline data is not return by `/scenarios/{id}` endpoint at `develop` branch.

When complete, this chart will replace the first pie chart ("People Connected").

### CODE REVIEW

**Comment by vgeorge** [comment]
Discussed this now with @olafveerman, we are keeping the initial approach of implement a stacked bar as described at #188. The popup should include the population connected between timesteps, as this will not be a information easily perceived at the chart.

**Comment by vgeorge** [comment]
Sorry, @olafveerman, I misundestood that. Here is the updated chart:

Screenshot 2019-08-28 20 08 13

**Comment by vgeorge** [comment]
Popover added, @danielfdsilva. There are still some issues with underlying data, but the general structure is ready to be styled.

**Comment by danielfdsilva** [comment]
@vgeorge site breaks with the following error, after selecting a country
```
error TypeError: "can't convert undefined to object"
    renderPopulationPopover Charts.js:161
    render Charts.js:557
    e countries:1
    routerMiddleware middleware.js:25
```

**Comment by danielfdsilva** [comment]
@vgeorge Popover was styled.
There are some problems with the connected population of the last year:

Malawi:
image

**Pull request merged**
