### PR TITLE
About page updates

### PR DESCRIPTION
**Pull request by danielfdsilva**
Missing:
- [ ] Add missing logos to the *Consortium* section (Cambridge, ABB, and Google) - according with https://github.com/global-electrification-platform/explorer/issues/153#issuecomment-532228141
- [ ] Add 2 missing logos to the *In collaboration with* section

Note:
The provided UK Aid logo was white and didn't work with the background. We downloaded the color version from https://www.ukaiddirect.org/

### CODE REVIEW

**Comment by nicolinalindblad** [comment]
@danielfdsilva We are still uploading logos, 4 more in the pipeline for _In Collaboration With._  Please let us know if these are not of good quality.

**Comment by nicolinalindblad** [comment]
Have uploaded the rest of the consortium, however, some only found on the internet, if you find of better quality please use that, thanks

**Comment by olafveerman** [comment]
@vgeorge Added the remaining logos. This is ready for review and deploy,

image

**Comment by olafveerman** [comment]
cc @nicolinalindblad ^

**Comment by vgeorge** [comment]
I've set links to open in a separate tab. Merging.

**Pull request merged**
