### PR TITLE
Production release for Updated About Page

### PR DESCRIPTION
**Pull request by EricSoroos**
@vgeorge Before we merge this, we need to address https://github.com/global-electrification-platform/explorer/pull/267#issuecomment-603945388 in the CI system.

### CODE REVIEW

**Comment by vgeorge** [comment]
@EricSoroos, I'm not sure if I understood the comment. If you need to use environment variables to pass the Mapbox key at the building step, this command should work:

    MB_TOKEN=<custom_mb_token> yarn build

Please let me know if this is not the issue.

**Comment by EricSoroos** [comment]
@vgeorge The problem is that the CI/CD that generates the production version of the site has the old mapbox key configured in environment variables, so when we merged to master the last time, the configuration change in default.js wasn't respected.  I had to build and push manually to make the site work. Clearly I'd rather have the CI/CD do the work. 

I don't have admin on the CI setup, so I can't make that change.

**Comment by vgeorge** [comment]
@EricSoroos I sent you a member invitation to `global-electrification-platform` organization. Once you accept, I'll promote you to owner and you should be able to make changes in CircleCI.

**Comment by EricSoroos** [comment]
Thanks, I just accepted.

**Comment by vgeorge** [comment]
@EricSoroos your user was promoted, now you should be able to access CircleCI and perform changes. Please let me know otherwise.

**Comment by EricSoroos** [comment]
@vgeorge Looks like that worked, I added the environment variable to CircleCi, I'm not sure why I had to, but the deploy was successful this time.

**Comment by vgeorge** [comment]
Good to know it worked, @EricSoroos. If no `MB_TOKEN` is set, the token at [this line](https://github.com/global-electrification-platform/explorer/blob/develop/app/assets/scripts/config/defaults.js#L10) will be used. Just wanted to confirm that you are aware of this.

**Pull request merged**
